/**
 * Données du module Vocabulaire — v2 enrichi (~500 mots)
 * Structure : { id, hanzi, pinyin, french, theme, level, jpKanji?, jpNote?, example? }
 * Les mots existants (w1-w87) sont conservés.
 * Nouveaux mots à partir de w88.
 */

const vocabularyData = {
  id: 'vocabulary',
  title: 'Vocabulaire',
  themes: {
    salutations: { name: 'Salutations & Politesse', icon: '👋' },
    famille: { name: 'Famille & Relations', icon: '👨‍👩‍👧‍👧' },
    quotidien: { name: 'Vie quotidienne', icon: '☕' },
    nombres: { name: 'Nombres & Quantité', icon: '🔢' },
    nourriture: { name: 'Nourriture & Boissons', icon: '🍜' },
    voyage: { name: 'Voyage & Direction', icon: '✈️' },
    travail: { name: 'Travail & Études', icon: '💼' },
    nature: { name: 'Nature & Plantes', icon: '🌿' },
    couleurs: { name: 'Couleurs & Formes', icon: '🎨' },
    corps: { name: 'Corps humain', icon: '🧍' },
    vetements: { name: 'Vêtements', icon: '👕' },
    maison: { name: 'Maison & Meubles', icon: '🏠' },
    transport: { name: 'Transports', icon: '🚌' },
    temps: { name: 'Temps & Heure', icon: '⏰' },
    meteo: { name: 'Météo & Saisons', icon: '🌤️' },
    animaux: { name: 'Animaux', icon: '🐕' },
    emotions: { name: 'Émotions & Sentiments', icon: '😊' },
    sport: { name: 'Sports & Loisirs', icon: '⚽' },
    sante: { name: 'Santé & Urgences', icon: '🏥' },
    ville: { name: 'Ville & Lieux', icon: '🏙️' },
    adjectifs: { name: 'Adjectifs courants', icon: '📝' },
    verbes: { name: 'Verbes courants', icon: '🏃' },
  },
  words: [
    // ============================================================
    // NIVEAU DÉBUTANT (~220 mots)
    // ============================================================

    // --- Salutations & Politesse (18 mots) ---
    { id: 'w1', hanzi: '你好', pinyin: 'nǐ hǎo', french: 'Bonjour / Salut', theme: 'salutations', level: 'debutant' },
    { id: 'w2', hanzi: '再见', pinyin: 'zài jiàn', french: 'Au revoir', theme: 'salutations', level: 'debutant' },
    { id: 'w3', hanzi: '谢谢', pinyin: 'xiè xiè', french: 'Merci', theme: 'salutations', level: 'debutant' },
    { id: 'w4', hanzi: '对不起', pinyin: 'duì bu qǐ', french: 'Pardon / Désolé', theme: 'salutations', level: 'debutant' },
    { id: 'w5', hanzi: '没关系', pinyin: 'méi guān xì', french: 'Pas de problème', theme: 'salutations', level: 'debutant', jpKanji: true, jpNote: '关系 (guānxì) = relation. En japonais 関係 = kankei.' },
    { id: 'w6', hanzi: '请', pinyin: 'qǐng', french: 'S\'il vous plaît', theme: 'salutations', level: 'debutant', jpKanji: true, jpNote: 'Même caractère que 請 en japonais.' },
    { id: 'w7', hanzi: '不客气', pinyin: 'bú kè qì', french: 'De rien', theme: 'salutations', level: 'debutant' },
    { id: 'w8', hanzi: '早上好', pinyin: 'zǎo shang hǎo', french: 'Bonjour (matin)', theme: 'salutations', level: 'debutant' },
    { id: 'w9', hanzi: '晚上好', pinyin: 'wǎn shang hǎo', french: 'Bonsoir', theme: 'salutations', level: 'debutant' },
    { id: 'w88', hanzi: '下午好', pinyin: 'xià wǔ hǎo', french: 'Bonjour (après-midi)', theme: 'salutations', level: 'debutant' },
    { id: 'w89', hanzi: '晚安', pinyin: 'wǎn ān', french: 'Bonne nuit', theme: 'salutations', level: 'debutant' },
    { id: 'w90', hanzi: '你好吗？', pinyin: 'nǐ hǎo ma', french: 'Comment vas-tu ?', theme: 'salutations', level: 'debutant' },
    { id: 'w91', hanzi: '我很好', pinyin: 'wǒ hěn hǎo', french: 'Je vais bien', theme: 'salutations', level: 'debutant' },
    { id: 'w92', hanzi: '你呢？', pinyin: 'nǐ ne', french: 'Et toi ?', theme: 'salutations', level: 'debutant' },
    { id: 'w93', hanzi: '欢迎', pinyin: 'huān yíng', french: 'Bienvenue', theme: 'salutations', level: 'debutant' },
    { id: 'w94', hanzi: '明天见', pinyin: 'míng tiān jiàn', french: 'À demain', theme: 'salutations', level: 'debutant' },
    { id: 'w95', hanzi: '回头见', pinyin: 'huí tóu jiàn', french: 'À tout à l\'heure', theme: 'salutations', level: 'debutant' },
    { id: 'w96', hanzi: '辛苦了', pinyin: 'xīn kǔ le', french: 'Bon travail / Merci pour ton effort', theme: 'salutations', level: 'debutant', jpNote: 'Expression typique chinoise. Se dit spontanément quand qqn a travaillé dur. Pas d\'équivalent direct en français ni japonais.' },

    // --- Famille & Relations (18 mots) ---
    { id: 'w10', hanzi: '爸爸', pinyin: 'bà ba', french: 'Papa', theme: 'famille', level: 'debutant', jpKanji: true, jpNote: '父 (chichi) en japonais. Redoublement typique chinois.' },
    { id: 'w11', hanzi: '妈妈', pinyin: 'mā ma', french: 'Maman', theme: 'famille', level: 'debutant', jpKanji: true, jpNote: '母 (haha) en japonais.' },
    { id: 'w12', hanzi: '哥哥', pinyin: 'gē ge', french: 'Grand frère', theme: 'famille', level: 'debutant', jpKanji: true, jpNote: '兄 (ani) en japonais.' },
    { id: 'w13', hanzi: '姐姐', pinyin: 'jiě jie', french: 'Grande sœur', theme: 'famille', level: 'debutant' },
    { id: 'w14', hanzi: '妹妹', pinyin: 'mèi mei', french: 'Petite sœur', theme: 'famille', level: 'debutant' },
    { id: 'w15', hanzi: '朋友', pinyin: 'péng yǒu', french: 'Ami(e)', theme: 'famille', level: 'debutant', jpKanji: true, jpNote: '友人 (yūjin) en japonais.' },
    { id: 'w97', hanzi: '爷爷', pinyin: 'yé ye', french: 'Grand-père paternel', theme: 'famille', level: 'debutant' },
    { id: 'w98', hanzi: '奶奶', pinyin: 'nǎi nai', french: 'Grand-mère paternelle', theme: 'famille', level: 'debutant' },
    { id: 'w99', hanzi: '弟弟', pinyin: 'dì di', french: 'Petit frère', theme: 'famille', level: 'debutant' },
    { id: 'w100', hanzi: '儿子', pinyin: 'ér zi', french: 'Fils', theme: 'famille', level: 'debutant' },
    { id: 'w101', hanzi: '女儿', pinyin: 'nǚ ér', french: 'Fille (enfant)', theme: 'famille', level: 'debutant' },
    { id: 'w102', hanzi: '丈夫', pinyin: 'zhàng fu', french: 'Mari', theme: 'famille', level: 'debutant', jpKanji: true, jpNote: '夫 = otto en japonais.' },
    { id: 'w103', hanzi: '妻子', pinyin: 'qī zi', french: 'Femme / Épouse', theme: 'famille', level: 'debutant' },
    { id: 'w104', hanzi: '孩子', pinyin: 'hái zi', french: 'Enfant', theme: 'famille', level: 'debutant' },
    { id: 'w105', hanzi: '同学', pinyin: 'tóng xué', french: 'Camarade de classe', theme: 'famille', level: 'debutant', jpKanji: true, jpNote: '同学 (dōgaku) en japonais = même école.' },

    // --- Nombres & Quantité (20 mots) ---
    { id: 'w16', hanzi: '一', pinyin: 'yī', french: 'Un', theme: 'nombres', level: 'debutant', jpKanji: true, jpNote: '一 = ichi/ひと' },
    { id: 'w17', hanzi: '二', pinyin: 'èr', french: 'Deux', theme: 'nombres', level: 'debutant', jpKanji: true, jpNote: '二 = ni/ふた' },
    { id: 'w18', hanzi: '三', pinyin: 'sān', french: 'Trois', theme: 'nombres', level: 'debutant', jpKanji: true },
    { id: 'w19', hanzi: '四', pinyin: 'sì', french: 'Quatre', theme: 'nombres', level: 'debutant', jpKanji: true, jpNote: '四 = shi/よん' },
    { id: 'w20', hanzi: '五', pinyin: 'wǔ', french: 'Cinq', theme: 'nombres', level: 'debutant', jpKanji: true },
    { id: 'w21', hanzi: '六', pinyin: 'liù', french: 'Six', theme: 'nombres', level: 'debutant', jpKanji: true, jpNote: '六 = roku/む' },
    { id: 'w22', hanzi: '七', pinyin: 'qī', french: 'Sept', theme: 'nombres', level: 'debutant', jpKanji: true },
    { id: 'w23', hanzi: '八', pinyin: 'bā', french: 'Huit', theme: 'nombres', level: 'debutant', jpKanji: true },
    { id: 'w24', hanzi: '九', pinyin: 'jiǔ', french: 'Neuf', theme: 'nombres', level: 'debutant', jpKanji: true },
    { id: 'w25', hanzi: '十', pinyin: 'shí', french: 'Dix', theme: 'nombres', level: 'debutant', jpKanji: true },
    { id: 'w26', hanzi: '百', pinyin: 'bǎi', french: 'Cent', theme: 'nombres', level: 'debutant', jpKanji: true, jpNote: '百 = hyaku' },
    { id: 'w27', hanzi: '千', pinyin: 'qiān', french: 'Mille', theme: 'nombres', level: 'debutant', jpKanji: true },
    { id: 'w106', hanzi: '万', pinyin: 'wàn', french: 'Dix mille', theme: 'nombres', level: 'debutant', jpKanji: true, jpNote: '万 = man/ばん. Attention : le chinois compte en 万 (10k) pas en milliers !' },
    { id: 'w107', hanzi: '零', pinyin: 'líng', french: 'Zéro', theme: 'nombres', level: 'debutant', jpKanji: true, jpNote: '零 = rei/れい en japonais' },
    { id: 'w108', hanzi: '半', pinyin: 'bàn', french: 'Demi / Moitié', theme: 'nombres', level: 'debutant', jpKanji: true, jpNote: '半 = han/en japonais (半分)' },
    { id: 'w109', hanzi: '几', pinyin: 'jǐ', french: 'Combien (petit nombre)', theme: 'nombres', level: 'debutant' },
    { id: 'w110', hanzi: '多少', pinyin: 'duō shao', french: 'Combien (grand nombre / prix)', theme: 'nombres', level: 'debutant' },
    { id: 'w111', hanzi: '第一个', pinyin: 'dì yī gè', french: 'Le premier', theme: 'nombres', level: 'debutant' },
    { id: 'w112', hanzi: '两个', pinyin: 'liǎng gè', french: 'Deux (classificateur)', theme: 'nombres', level: 'debutant', jpNote: '两 (liǎng) pour "deux" avec classificateur, 二 (èr) pour compter.' },

    // --- Corps humain (20 mots) ---
    { id: 'w113', hanzi: '头', pinyin: 'tóu', french: 'Tête', theme: 'corps', level: 'debutant', jpKanji: true, jpNote: '頭 = atama, même caractère (simplifié).' },
    { id: 'w114', hanzi: '眼睛', pinyin: 'yǎn jīng', french: 'Œil / Yeux', theme: 'corps', level: 'debutant', jpKanji: true, jpNote: '眼 = me. 睛 n\'existe pas seul en japonais.' },
    { id: 'w115', hanzi: '耳朵', pinyin: 'ěr duo', french: 'Oreille(s)', theme: 'corps', level: 'debutant', jpKanji: true, jpNote: '耳 = mimi. Même caractère !' },
    { id: 'w116', hanzi: '鼻子', pinyin: 'bí zi', french: 'Nez', theme: 'corps', level: 'debutant', jpKanji: true, jpNote: '鼻 = hana. Même caractère !' },
    { id: 'w117', hanzi: '嘴巴', pinyin: 'zuǐ ba', french: 'Bouche', theme: 'corps', level: 'debutant' },
    { id: 'w118', hanzi: '牙齿', pinyin: 'yá chǐ', french: 'Dent(s)', theme: 'corps', level: 'debutant' },
    { id: 'w119', hanzi: '舌头', pinyin: 'shé tou', french: 'Langue', theme: 'corps', level: 'debutant' },
    { id: 'w120', hanzi: '头发', pinyin: 'tóu fa', french: 'Cheveux', theme: 'corps', level: 'debutant' },
    { id: 'w121', hanzi: '脸', pinyin: 'liǎn', french: 'Visage', theme: 'corps', level: 'debutant' },
    { id: 'w122', hanzi: '脖子', pinyin: 'bó zi', french: 'Cou', theme: 'corps', level: 'debutant' },
    { id: 'w123', hanzi: '肩膀', pinyin: 'jiān bǎng', french: 'Épaule', theme: 'corps', level: 'debutant' },
    { id: 'w124', hanzi: '手', pinyin: 'shǒu', french: 'Main', theme: 'corps', level: 'debutant', jpKanji: true, jpNote: '手 = te, caractère identique !' },
    { id: 'w125', hanzi: '手指', pinyin: 'shǒu zhǐ', french: 'Doigt', theme: 'corps', level: 'debutant' },
    { id: 'w126', hanzi: '脚', pinyin: 'jiǎo', french: 'Pied', theme: 'corps', level: 'debutant', jpKanji: true, jpNote: '脚 = ashi, même caractère !' },
    { id: 'w127', hanzi: '腿', pinyin: 'tuǐ', french: 'Jambe', theme: 'corps', level: 'debutant' },
    { id: 'w128', hanzi: '胳膊', pinyin: 'gē bo', french: 'Bras', theme: 'corps', level: 'debutant' },
    { id: 'w129', hanzi: '肚子', pinyin: 'dù zi', french: 'Ventre', theme: 'corps', level: 'debutant' },
    { id: 'w130', hanzi: '背', pinyin: 'bèi', french: 'Dos', theme: 'corps', level: 'debutant', jpKanji: true, jpNote: '背 = se, même caractère.' },
    { id: 'w131', hanzi: '心脏', pinyin: 'xīn zàng', french: 'Cœur (organe)', theme: 'corps', level: 'debutant', jpKanji: true, jpNote: '心臓 = shinzō. 心 = kokoro.' },

    // --- Nourriture & Boissons (28 mots) ---
    { id: 'w38', hanzi: '吃', pinyin: 'chī', french: 'Manger', theme: 'nourriture', level: 'debutant' },
    { id: 'w39', hanzi: '喝', pinyin: 'hē', french: 'Boire', theme: 'nourriture', level: 'debutant' },
    { id: 'w40', hanzi: '苹果', pinyin: 'píng guǒ', french: 'Pomme', theme: 'nourriture', level: 'debutant' },
    { id: 'w41', hanzi: '牛奶', pinyin: 'niú nǎi', french: 'Lait', theme: 'nourriture', level: 'debutant' },
    { id: 'w42', hanzi: '面包', pinyin: 'miàn bāo', french: 'Pain', theme: 'nourriture', level: 'debutant' },
    { id: 'w43', hanzi: '肉', pinyin: 'ròu', french: 'Viande', theme: 'nourriture', level: 'debutant', jpKanji: true, jpNote: '肉 = niku, identique.' },
    { id: 'w44', hanzi: '鸡蛋', pinyin: 'jī dàn', french: 'Œuf (poule)', theme: 'nourriture', level: 'debutant' },
    { id: 'w132', hanzi: '牛肉', pinyin: 'niú ròu', french: 'Bœuf (viande)', theme: 'nourriture', level: 'debutant' },
    { id: 'w133', hanzi: '猪肉', pinyin: 'zhū ròu', french: 'Porc', theme: 'nourriture', level: 'debutant' },
    { id: 'w134', hanzi: '鸡肉', pinyin: 'jī ròu', french: 'Poulet (viande)', theme: 'nourriture', level: 'debutant' },
    { id: 'w135', hanzi: '鱼', pinyin: 'yú', french: 'Poisson', theme: 'nourriture', level: 'debutant', jpKanji: true, jpNote: '魚 = sakana/uo. Même caractère.' },
    { id: 'w136', hanzi: '蔬菜', pinyin: 'shū cài', french: 'Légumes', theme: 'nourriture', level: 'debutant' },
    { id: 'w137', hanzi: '水果', pinyin: 'shuǐ guǒ', french: 'Fruits', theme: 'nourriture', level: 'debutant' },
    { id: 'w138', hanzi: '香蕉', pinyin: 'xiāng jiāo', french: 'Banane', theme: 'nourriture', level: 'debutant' },
    { id: 'w139', hanzi: '橙子', pinyin: 'chéng zi', french: 'Orange (fruit)', theme: 'nourriture', level: 'debutant' },
    { id: 'w140', hanzi: '西瓜', pinyin: 'xī guā', french: 'Pastèque', theme: 'nourriture', level: 'debutant' },
    { id: 'w141', hanzi: '米饭', pinyin: 'mǐ fàn', french: 'Riz cuit', theme: 'nourriture', level: 'debutant' },
    { id: 'w142', hanzi: '面条', pinyin: 'miàn tiáo', french: 'Nouilles', theme: 'nourriture', level: 'debutant' },
    { id: 'w143', hanzi: '汤', pinyin: 'tāng', french: 'Soupe / Potage', theme: 'nourriture', level: 'debutant', jpKanji: true, jpNote: '湯 = yu (eau chaude) en japonais. Attention : en chinois = soupe !' },
    { id: 'w144', hanzi: '糖', pinyin: 'táng', french: 'Sucre / Bonbon', theme: 'nourriture', level: 'debutant' },
    { id: 'w145', hanzi: '盐', pinyin: 'yán', french: 'Sel', theme: 'nourriture', level: 'debutant', jpKanji: true, jpNote: '塩 = shio, différent en japonais.' },
    { id: 'w146', hanzi: '油', pinyin: 'yóu', french: 'Huile', theme: 'nourriture', level: 'debutant', jpKanji: true, jpNote: '油 = abura, même caractère.' },
    { id: 'w147', hanzi: '蛋糕', pinyin: 'dàn gāo', french: 'Gâteau', theme: 'nourriture', level: 'debutant' },
    { id: 'w148', hanzi: '冰淇淋', pinyin: 'bīng qí lín', french: 'Glace (crème glacée)', theme: 'nourriture', level: 'debutant' },
    { id: 'w149', hanzi: '可乐', pinyin: 'kě lè', french: 'Coca / Soda', theme: 'nourriture', level: 'debutant' },
    { id: 'w380', hanzi: '汽水', pinyin: 'qì shuǐ', french: 'Soda / Boisson gazeuse', theme: 'nourriture', level: 'debutant' },

    // --- Vêtements (18 mots) ---
    { id: 'w36', hanzi: '衣服', pinyin: 'yī fu', french: 'Vêtements', theme: 'vetements', level: 'debutant' },
    { id: 'w150', hanzi: '衬衫', pinyin: 'chèn shān', french: 'Chemise', theme: 'vetements', level: 'debutant' },
    { id: 'w151', hanzi: '裤子', pinyin: 'kù zi', french: 'Pantalon', theme: 'vetements', level: 'debutant' },
    { id: 'w152', hanzi: '裙子', pinyin: 'qún zi', french: 'Jupe / Robe', theme: 'vetements', level: 'debutant' },
    { id: 'w153', hanzi: '鞋子', pinyin: 'xié zi', french: 'Chaussures', theme: 'vetements', level: 'debutant' },
    { id: 'w154', hanzi: '袜子', pinyin: 'wà zi', french: 'Chaussettes', theme: 'vetements', level: 'debutant' },
    { id: 'w155', hanzi: '帽子', pinyin: 'mào zi', french: 'Chapeau', theme: 'vetements', level: 'debutant' },
    { id: 'w156', hanzi: '外套', pinyin: 'wài tào', french: 'Manteau / Veste', theme: 'vetements', level: 'debutant' },
    { id: 'w157', hanzi: '毛衣', pinyin: 'máo yī', french: 'Pull (laine)', theme: 'vetements', level: 'debutant' },
    { id: 'w158', hanzi: '牛仔裤', pinyin: 'niú zǎi kù', french: 'Jean (pantalon)', theme: 'vetements', level: 'debutant' },
    { id: 'w159', hanzi: '领带', pinyin: 'lǐng dài', french: 'Cravate', theme: 'vetements', level: 'debutant' },
    { id: 'w160', hanzi: '口袋', pinyin: 'kǒu dài', french: 'Poche', theme: 'vetements', level: 'debutant' },

    // --- Maison & Meubles (18 mots) ---
    { id: 'w37', hanzi: '家', pinyin: 'jiā', french: 'Maison / Famille', theme: 'maison', level: 'debutant', jpKanji: true, jpNote: '家 = ie/うち/か' },
    { id: 'w161', hanzi: '门', pinyin: 'mén', french: 'Porte', theme: 'maison', level: 'debutant', jpKanji: true, jpNote: '門 = mon/kado. Même caractère (简化 : 门).' },
    { id: 'w162', hanzi: '窗户', pinyin: 'chuāng hu', french: 'Fenêtre', theme: 'maison', level: 'debutant' },
    { id: 'w163', hanzi: '床', pinyin: 'chuáng', french: 'Lit', theme: 'maison', level: 'debutant', jpKanji: true, jpNote: '床 = toko (sol) en japonais. FAUX AMI : en chinois = lit !' },
    { id: 'w164', hanzi: '桌子', pinyin: 'zhuō zi', french: 'Table', theme: 'maison', level: 'debutant' },
    { id: 'w165', hanzi: '椅子', pinyin: 'yǐ zi', french: 'Chaise', theme: 'maison', level: 'debutant' },
    { id: 'w166', hanzi: '房间', pinyin: 'fáng jiān', french: 'Chambre / Pièce', theme: 'maison', level: 'debutant' },
    { id: 'w167', hanzi: '厨房', pinyin: 'chú fáng', french: 'Cuisine', theme: 'maison', level: 'debutant' },
    { id: 'w168', hanzi: '厕所', pinyin: 'cè suǒ', french: 'Toilettes', theme: 'maison', level: 'debutant' },
    { id: 'w169', hanzi: '客厅', pinyin: 'kè tīng', french: 'Salon', theme: 'maison', level: 'debutant' },
    { id: 'w170', hanzi: '灯', pinyin: 'dēng', french: 'Lampe / Lumière', theme: 'maison', level: 'debutant', jpKanji: true, jpNote: '灯 = hi/あかり' },
    { id: 'w171', hanzi: '钥匙', pinyin: 'yào shi', french: 'Clé', theme: 'maison', level: 'debutant' },
    { id: 'w172', hanzi: '镜子', pinyin: 'jìng zi', french: 'Miroir', theme: 'maison', level: 'debutant', jpKanji: true, jpNote: '鏡 = kagami, même caractère.' },

    // --- Animaux (15 mots) ---
    { id: 'w173', hanzi: '狗', pinyin: 'gǒu', french: 'Chien', theme: 'animaux', level: 'debutant' },
    { id: 'w174', hanzi: '猫', pinyin: 'māo', french: 'Chat', theme: 'animaux', level: 'debutant' },
    { id: 'w175', hanzi: '鸟', pinyin: 'niǎo', french: 'Oiseau', theme: 'animaux', level: 'debutant', jpKanji: true, jpNote: '鳥 = tori, même caractère (simplifié).' },
    { id: 'w176', hanzi: '鱼', pinyin: 'yú', french: 'Poisson', theme: 'animaux', level: 'debutant', jpKanji: true, jpNote: '魚 = sakana, identique.' },
    { id: 'w177', hanzi: '马', pinyin: 'mǎ', french: 'Cheval', theme: 'animaux', level: 'debutant', jpKanji: true, jpNote: '馬 = uma, identique.' },

    // --- Transports (15 mots) ---
    { id: 'w178', hanzi: '车', pinyin: 'chē', french: 'Véhicule / Voiture', theme: 'transport', level: 'debutant', jpKanji: true, jpNote: '車 = kuruma, identique.' },
    { id: 'w179', hanzi: '公共汽车', pinyin: 'gōng gòng qì chē', french: 'Bus', theme: 'transport', level: 'debutant' },
    { id: 'w381', hanzi: '公交车', pinyin: 'gōng jiāo chē', french: 'Bus (oral, courant)', theme: 'transport', level: 'debutant' },
    { id: 'w180', hanzi: '地铁', pinyin: 'dì tiě', french: 'Métro', theme: 'transport', level: 'debutant' },
    { id: 'w181', hanzi: '出租车', pinyin: 'chū zū chē', french: 'Taxi', theme: 'transport', level: 'debutant' },
    { id: 'w182', hanzi: '自行车', pinyin: 'zì xíng chē', french: 'Vélo', theme: 'transport', level: 'debutant' },
    { id: 'w183', hanzi: '飞机', pinyin: 'fēi jī', french: 'Avion', theme: 'transport', level: 'debutant' },
    { id: 'w184', hanzi: '火车', pinyin: 'huǒ chē', french: 'Train', theme: 'transport', level: 'debutant' },
    { id: 'w185', hanzi: '船', pinyin: 'chuán', french: 'Bateau', theme: 'transport', level: 'debutant', jpKanji: true, jpNote: '船 = fune, même caractère.' },

    // --- Temps & Heure (25 mots) ---
    { id: 'w186', hanzi: '今天', pinyin: 'jīn tiān', french: 'Aujourd\'hui', theme: 'temps', level: 'debutant', jpKanji: true, jpNote: '今日 (kyō). Même idée.' },
    { id: 'w187', hanzi: '明天', pinyin: 'míng tiān', french: 'Demain', theme: 'temps', level: 'debutant', jpKanji: true, jpNote: '明日 (ashita).' },
    { id: 'w188', hanzi: '昨天', pinyin: 'zuó tiān', french: 'Hier', theme: 'temps', level: 'debutant' },
    { id: 'w189', hanzi: '现在', pinyin: 'xiàn zài', french: 'Maintenant', theme: 'temps', level: 'debutant', jpKanji: true, jpNote: '現在 (genzai). Mêmes caractères !' },
    { id: 'w190', hanzi: '早上', pinyin: 'zǎo shang', french: 'Matin', theme: 'temps', level: 'debutant' },
    { id: 'w191', hanzi: '中午', pinyin: 'zhōng wǔ', french: 'Midi', theme: 'temps', level: 'debutant' },
    { id: 'w192', hanzi: '下午', pinyin: 'xià wǔ', french: 'Après-midi', theme: 'temps', level: 'debutant' },
    { id: 'w193', hanzi: '晚上', pinyin: 'wǎn shang', french: 'Soir', theme: 'temps', level: 'debutant' },
    { id: 'w194', hanzi: '小时', pinyin: 'xiǎo shí', french: 'Heure (durée)', theme: 'temps', level: 'debutant' },
    { id: 'w195', hanzi: '分钟', pinyin: 'fēn zhōng', french: 'Minute', theme: 'temps', level: 'debutant' },
    { id: 'w196', hanzi: '点钟', pinyin: 'diǎn zhōng', french: 'Heure (horloge)', theme: 'temps', level: 'debutant' },

    // --- Couleurs (12 mots) ---
    { id: 'w197', hanzi: '红色', pinyin: 'hóng sè', french: 'Rouge', theme: 'couleurs', level: 'debutant', jpKanji: true, jpNote: '赤 (aka). 红 est la version simplifiée.' },
    { id: 'w198', hanzi: '蓝色', pinyin: 'lán sè', french: 'Bleu', theme: 'couleurs', level: 'debutant' },
    { id: 'w199', hanzi: '绿色', pinyin: 'lǜ sè', french: 'Vert', theme: 'couleurs', level: 'debutant' },
    { id: 'w200', hanzi: '白色', pinyin: 'bái sè', french: 'Blanc', theme: 'couleurs', level: 'debutant', jpKanji: true, jpNote: '白 = shiro, identique.' },
    { id: 'w201', hanzi: '黑色', pinyin: 'hēi sè', french: 'Noir', theme: 'couleurs', level: 'debutant', jpKanji: true, jpNote: '黒 = kuro, même caractère.' },
    { id: 'w202', hanzi: '黄色', pinyin: 'huáng sè', french: 'Jaune', theme: 'couleurs', level: 'debutant', jpKanji: true, jpNote: '黄 = kiiro, identique.' },

    // --- Météo (10 mots) ---
    { id: 'w203', hanzi: '天气', pinyin: 'tiān qì', french: 'Temps (météo)', theme: 'meteo', level: 'debutant' },
    { id: 'w204', hanzi: '冷', pinyin: 'lěng', french: 'Froid', theme: 'meteo', level: 'debutant', jpKanji: true, jpNote: '冷 = rei/つめたい' },
    { id: 'w205', hanzi: '热', pinyin: 'rè', french: 'Chaud', theme: 'meteo', level: 'debutant', jpKanji: true, jpNote: '熱 = netsu, simplifié en 热' },
    { id: 'w206', hanzi: '下雨', pinyin: 'xià yǔ', french: 'Pleuvoir', theme: 'meteo', level: 'debutant' },
    { id: 'w207', hanzi: '下雪', pinyin: 'xià xuě', french: 'Neiger', theme: 'meteo', level: 'debutant' },
    { id: 'w208', hanzi: '晴天', pinyin: 'qíng tiān', french: 'Temps clair / Ensoleillé', theme: 'meteo', level: 'debutant' },
    { id: 'w209', hanzi: '风', pinyin: 'fēng', french: 'Vent', theme: 'meteo', level: 'debutant', jpKanji: true, jpNote: '風 = kaze, identique.' },
    { id: 'w210', hanzi: '春天', pinyin: 'chūn tiān', french: 'Printemps', theme: 'meteo', level: 'debutant' },

    // --- Ville & Lieux (15 mots) ---
    { id: 'w211', hanzi: '商店', pinyin: 'shāng diàn', french: 'Magasin / Boutique', theme: 'ville', level: 'debutant' },
    { id: 'w212', hanzi: '超市', pinyin: 'chāo shì', french: 'Supermarché', theme: 'ville', level: 'debutant' },
    { id: 'w213', hanzi: '公园', pinyin: 'gōng yuán', french: 'Parc', theme: 'ville', level: 'debutant' },
    { id: 'w214', hanzi: '图书馆', pinyin: 'tú shū guǎn', french: 'Bibliothèque', theme: 'ville', level: 'debutant' },
    { id: 'w215', hanzi: '银行', pinyin: 'yín háng', french: 'Banque', theme: 'ville', level: 'debutant', jpKanji: true, jpNote: '銀行 = ginkō, mêmes caractères !' },
    { id: 'w216', hanzi: '邮局', pinyin: 'yóu jú', french: 'Poste', theme: 'ville', level: 'debutant' },

    // --- Adjectifs courants débutant (18 mots) ---
    { id: 'w217', hanzi: '大', pinyin: 'dà', french: 'Grand', theme: 'adjectifs', level: 'debutant', jpKanji: true, jpNote: '大 = ōkii/だい, identique.' },
    { id: 'w218', hanzi: '小', pinyin: 'xiǎo', french: 'Petit', theme: 'adjectifs', level: 'debutant', jpKanji: true, jpNote: '小 = chīsai/しょう' },
    { id: 'w219', hanzi: '好', pinyin: 'hǎo', french: 'Bon', theme: 'adjectifs', level: 'debutant', jpKanji: true, jpNote: '好 = kō/すき (大好き)' },
    { id: 'w220', hanzi: '坏', pinyin: 'huài', french: 'Mauvais / Cassé', theme: 'adjectifs', level: 'debutant' },
    { id: 'w221', hanzi: '多', pinyin: 'duō', french: 'Beaucoup', theme: 'adjectifs', level: 'debutant', jpKanji: true, jpNote: '多 = ōi/た, identique.' },
    { id: 'w222', hanzi: '少', pinyin: 'shǎo', french: 'Peu', theme: 'adjectifs', level: 'debutant' },
    { id: 'w223', hanzi: '快', pinyin: 'kuài', french: 'Rapide / Vite', theme: 'adjectifs', level: 'debutant' },
    { id: 'w224', hanzi: '慢', pinyin: 'màn', french: 'Lent', theme: 'adjectifs', level: 'debutant' },
    { id: 'w225', hanzi: '新', pinyin: 'xīn', french: 'Nouveau', theme: 'adjectifs', level: 'debutant', jpKanji: true, jpNote: '新 = atarashī/しん' },
    { id: 'w226', hanzi: '旧', pinyin: 'jiù', french: 'Vieux / Ancien', theme: 'adjectifs', level: 'debutant', jpKanji: true, jpNote: '旧 = kyū (旧友, 旧式). Même caractère, sens similaire mais usage plus large en chinois.' },
    { id: 'w227', hanzi: '高', pinyin: 'gāo', french: 'Grand (taille) / Haut', theme: 'adjectifs', level: 'debutant', jpKanji: true, jpNote: '高 = takai/こう, identique.' },
    { id: 'w228', hanzi: '矮', pinyin: 'ǎi', french: 'Petit (taille)', theme: 'adjectifs', level: 'debutant' },

    // --- Verbes courants débutant (18 mots) ---
    { id: 'w229', hanzi: '去', pinyin: 'qù', french: 'Aller', theme: 'verbes', level: 'debutant', jpKanji: true, jpNote: '去 = いく/きょ (過去), sens similaire.' },
    { id: 'w230', hanzi: '来', pinyin: 'lái', french: 'Venir', theme: 'verbes', level: 'debutant', jpKanji: true, jpNote: '来 = kuru/らい, identique.' },
    { id: 'w231', hanzi: '看', pinyin: 'kàn', french: 'Regarder / Lire', theme: 'verbes', level: 'debutant' },
    { id: 'w232', hanzi: '听', pinyin: 'tīng', french: 'Écouter', theme: 'verbes', level: 'debutant' },
    { id: 'w233', hanzi: '说', pinyin: 'shuō', french: 'Parler / Dire', theme: 'verbes', level: 'debutant' },
    { id: 'w234', hanzi: '读', pinyin: 'dú', french: 'Lire (à voix haute)', theme: 'verbes', level: 'debutant' },
    { id: 'w235', hanzi: '写', pinyin: 'xiě', french: 'Écrire', theme: 'verbes', level: 'debutant' },
    { id: 'w236', hanzi: '坐', pinyin: 'zuò', french: 'S\'asseoir / Prendre (transport)', theme: 'verbes', level: 'debutant' },
    { id: 'w237', hanzi: '站', pinyin: 'zhàn', french: 'Être debout / Se lever', theme: 'verbes', level: 'debutant' },
    { id: 'w238', hanzi: '买', pinyin: 'mǎi', french: 'Acheter', theme: 'verbes', level: 'debutant' },
    { id: 'w239', hanzi: '卖', pinyin: 'mài', french: 'Vendre', theme: 'verbes', level: 'debutant' },
    { id: 'w240', hanzi: '给', pinyin: 'gěi', french: 'Donner', theme: 'verbes', level: 'debutant' },
    { id: 'w241', hanzi: '等', pinyin: 'děng', french: 'Attendre', theme: 'verbes', level: 'debutant' },
    { id: 'w242', hanzi: '住', pinyin: 'zhù', french: 'Habiter', theme: 'verbes', level: 'debutant' },

    // ============================================================
    // NIVEAU INTERMÉDIAIRE (~180 mots)
    // ============================================================

    // --- Voyage & Direction (20 mots) ---
    { id: 'w55', hanzi: '法国', pinyin: 'fǎ guó', french: 'France', theme: 'voyage', level: 'intermediaire' },
    { id: 'w56', hanzi: '中国', pinyin: 'zhōng guó', french: 'Chine', theme: 'voyage', level: 'intermediaire', jpKanji: true, jpNote: '中国 = chūgoku, mêmes caractères.' },
    { id: 'w57', hanzi: '日本', pinyin: 'rì běn', french: 'Japon', theme: 'voyage', level: 'intermediaire', jpKanji: true, jpNote: '日本 = nihon, identiques.' },
    { id: 'w58', hanzi: '医院', pinyin: 'yī yuàn', french: 'Hôpital', theme: 'voyage', level: 'intermediaire', jpKanji: true, jpNote: '医院 = iin, mêmes caractères.' },
    { id: 'w59', hanzi: '钱', pinyin: 'qián', french: 'Argent (monnaie)', theme: 'voyage', level: 'intermediaire', jpKanji: true, jpNote: '錢 = simplifié en 钱. Japonais dit お金 (okane), 銭 (sen) existe mais pour petite monnaie. Même kanji trad mais usage différent !' },
    { id: 'w60', hanzi: '贵', pinyin: 'guì', french: 'Cher', theme: 'voyage', level: 'intermediaire', jpKanji: true, jpNote: '貴 = toutoi/贵重' },
    { id: 'w61', hanzi: '便宜', pinyin: 'pián yi', french: 'Bon marché', theme: 'voyage', level: 'intermediaire' },
    { id: 'w243', hanzi: '酒店', pinyin: 'jiǔ diàn', french: 'Hôtel', theme: 'voyage', level: 'intermediaire' },
    { id: 'w244', hanzi: '护照', pinyin: 'hù zhào', french: 'Passeport', theme: 'voyage', level: 'intermediaire' },
    { id: 'w245', hanzi: '行李', pinyin: 'xíng li', french: 'Bagages', theme: 'voyage', level: 'intermediaire' },
    { id: 'w246', hanzi: '地图', pinyin: 'dì tú', french: 'Carte (géographique)', theme: 'voyage', level: 'intermediaire' },
    { id: 'w247', hanzi: '方向', pinyin: 'fāng xiàng', french: 'Direction', theme: 'voyage', level: 'intermediaire' },
    { id: 'w248', hanzi: '左边', pinyin: 'zuǒ biān', french: 'À gauche', theme: 'voyage', level: 'intermediaire', jpKanji: true, jpNote: '左 = hidari. 边 = côté (pas de équivalent en japonais). En chinois on ajoute 边 pour "côté" : 左边, 右边.' },
    { id: 'w249', hanzi: '右边', pinyin: 'yòu biān', french: 'À droite', theme: 'voyage', level: 'intermediaire', jpKanji: true, jpNote: '右 = migi. Même principe : 右 + 边. Japonais dit juste 右/migi sans suffixe.' },
    { id: 'w250', hanzi: '前面', pinyin: 'qián miàn', french: 'Devant', theme: 'voyage', level: 'intermediaire' },
    { id: 'w251', hanzi: '后面', pinyin: 'hòu miàn', french: 'Derrière', theme: 'voyage', level: 'intermediaire' },
    { id: 'w252', hanzi: '旁边', pinyin: 'páng biān', french: 'À côté', theme: 'voyage', level: 'intermediaire' },
    { id: 'w253', hanzi: '机场', pinyin: 'jī chǎng', french: 'Aéroport', theme: 'voyage', level: 'intermediaire' },
    { id: 'w254', hanzi: '火车站', pinyin: 'huǒ chē zhàn', french: 'Gare', theme: 'voyage', level: 'intermediaire' },
    { id: 'w255', hanzi: '车站', pinyin: 'chē zhàn', french: 'Arrêt de bus / Station', theme: 'voyage', level: 'intermediaire' },

    // --- Travail & Études (25 mots) ---
    { id: 'w50', hanzi: '学校', pinyin: 'xué xiào', french: 'École', theme: 'travail', level: 'intermediaire', jpKanji: true, jpNote: '学校 = gakkō' },
    { id: 'w51', hanzi: '老师', pinyin: 'lǎo shī', french: 'Professeur', theme: 'travail', level: 'intermediaire' },
    { id: 'w52', hanzi: '学生', pinyin: 'xué shēng', french: 'Étudiant', theme: 'travail', level: 'intermediaire', jpKanji: true, jpNote: '学生 = gakusei' },
    { id: 'w53', hanzi: '汉语', pinyin: 'hàn yǔ', french: 'Langue chinoise', theme: 'travail', level: 'intermediaire' },
    { id: 'w54', hanzi: '英语', pinyin: 'yīng yǔ', french: 'Langue anglaise', theme: 'travail', level: 'intermediaire' },
    { id: 'w256', hanzi: '法语', pinyin: 'fǎ yǔ', french: 'Langue française', theme: 'travail', level: 'intermediaire' },
    { id: 'w257', hanzi: '日语', pinyin: 'rì yǔ', french: 'Langue japonaise', theme: 'travail', level: 'intermediaire' },
    { id: 'w258', hanzi: '上班', pinyin: 'shàng bān', french: 'Aller au travail', theme: 'travail', level: 'intermediaire', jpKanji: true, jpNote: '上 + 班 = "monter au poste". En japonais : 出勤 (shukkin).' },
    { id: 'w259', hanzi: '下班', pinyin: 'xià bān', french: 'Sortir du travail', theme: 'travail', level: 'intermediaire', jpKanji: true, jpNote: '下 + 班 = "descendre du poste". En japonais : 退勤 (taikin).' },
    { id: 'w260', hanzi: '办公室', pinyin: 'bàn gōng shì', french: 'Bureau (pièce)', theme: 'travail', level: 'intermediaire' },
    { id: 'w261', hanzi: '公司', pinyin: 'gōng sī', french: 'Entreprise / Compagnie', theme: 'travail', level: 'intermediaire' },
    { id: 'w262', hanzi: '同事', pinyin: 'tóng shì', french: 'Collègue', theme: 'travail', level: 'intermediaire' },
    { id: 'w263', hanzi: '考试', pinyin: 'kǎo shì', french: 'Examen', theme: 'travail', level: 'intermediaire' },
    { id: 'w264', hanzi: '作业', pinyin: 'zuò yè', french: 'Devoirs', theme: 'travail', level: 'intermediaire' },
    { id: 'w265', hanzi: '教室', pinyin: 'jiào shì', french: 'Salle de classe', theme: 'travail', level: 'intermediaire' },
    { id: 'w266', hanzi: '词典', pinyin: 'cí diǎn', french: 'Dictionnaire', theme: 'travail', level: 'intermediaire' },
    { id: 'w267', hanzi: '笔记', pinyin: 'bǐ jì', french: 'Notes (cours)', theme: 'travail', level: 'intermediaire', jpKanji: true, jpNote: '筆記 = hikki en japonais (prendre des notes).' },

    // --- Vie quotidienne intermédiaire (25 mots) ---
    { id: 'w45', hanzi: '时间', pinyin: 'shí jiān', french: 'Temps (durée)', theme: 'quotidien', level: 'intermediaire' },
    { id: 'w62', hanzi: '喜欢', pinyin: 'xǐ huān', french: 'Aimer / Apprécier', theme: 'quotidien', level: 'intermediaire' },
    { id: 'w63', hanzi: '知道', pinyin: 'zhī dào', french: 'Savoir (fait)', theme: 'quotidien', level: 'intermediaire' },
    { id: 'w64', hanzi: '认识', pinyin: 'rèn shi', french: 'Connaître (qqn)', theme: 'quotidien', level: 'intermediaire', jpKanji: true, jpNote: '⚠️ Attention : 認識 en japonais = ninshiki (reconnaissance/cognition). En chinois, 认识 signifie "connaître quelqu\'un". Pas le même sens !' },
    { id: 'w49', hanzi: '星期', pinyin: 'xīng qī', french: 'Semaine', theme: 'quotidien', level: 'intermediaire' },
    { id: 'w268', hanzi: '月', pinyin: 'yuè', french: 'Mois / Lune', theme: 'quotidien', level: 'intermediaire', jpKanji: true, jpNote: '月 = tsuki/げつ' },
    { id: 'w269', hanzi: '年', pinyin: 'nián', french: 'An / Année', theme: 'quotidien', level: 'intermediaire', jpKanji: true, jpNote: '年 = toshi/ねん' },
    { id: 'w270', hanzi: '号码', pinyin: 'hào mǎ', french: 'Numéro', theme: 'quotidien', level: 'intermediaire' },
    { id: 'w271', hanzi: '名字', pinyin: 'míng zì', french: 'Nom (prénom)', theme: 'quotidien', level: 'intermediaire' },
    { id: 'w272', hanzi: '生日', pinyin: 'shēng rì', french: 'Anniversaire (date)', theme: 'quotidien', level: 'intermediaire' },
    { id: 'w273', hanzi: '年纪', pinyin: 'nián jì', french: 'Âge', theme: 'quotidien', level: 'intermediaire' },
    { id: 'w274', hanzi: '手机', pinyin: 'shǒu jī', french: 'Téléphone portable', theme: 'quotidien', level: 'intermediaire' },

    // --- Émotions & Sentiments (20 mots) ---
    { id: 'w275', hanzi: '高兴', pinyin: 'gāo xìng', french: 'Content / Joyeux', theme: 'emotions', level: 'intermediaire' },
    { id: 'w276', hanzi: '生气', pinyin: 'shēng qì', french: 'Fâché / En colère', theme: 'emotions', level: 'intermediaire' },
    { id: 'w277', hanzi: '难过', pinyin: 'nán guò', french: 'Triste', theme: 'emotions', level: 'intermediaire' },
    { id: 'w278', hanzi: '害怕', pinyin: 'hài pà', french: 'Avoir peur', theme: 'emotions', level: 'intermediaire' },
    { id: 'w279', hanzi: '着急', pinyin: 'zháo jí', french: 'Être pressé / Inquiet', theme: 'emotions', level: 'intermediaire' },
    { id: 'w280', hanzi: '累', pinyin: 'lèi', french: 'Fatigué', theme: 'emotions', level: 'intermediaire' },
    { id: 'w281', hanzi: '饿', pinyin: 'è', french: 'Avoir faim', theme: 'emotions', level: 'intermediaire' },
    { id: 'w282', hanzi: '渴', pinyin: 'kě', french: 'Avoir soif', theme: 'emotions', level: 'intermediaire' },
    { id: 'w283', hanzi: '开心', pinyin: 'kāi xīn', french: 'Heureux', theme: 'emotions', level: 'intermediaire' },

    // --- Adjectifs intermédiaires (20 mots) ---
    { id: 'w284', hanzi: '好吃', pinyin: 'hǎo chī', french: 'Bon (à manger)', theme: 'adjectifs', level: 'intermediaire' },
    { id: 'w285', hanzi: '好喝', pinyin: 'hǎo hē', french: 'Bon (à boire)', theme: 'adjectifs', level: 'intermediaire' },
    { id: 'w286', hanzi: '好看', pinyin: 'hǎo kàn', french: 'Beau / Joli à regarder', theme: 'adjectifs', level: 'intermediaire' },
    { id: 'w287', hanzi: '好听', pinyin: 'hǎo tīng', french: 'Agréable à écouter', theme: 'adjectifs', level: 'intermediaire' },
    { id: 'w288', hanzi: '难', pinyin: 'nán', french: 'Difficile', theme: 'adjectifs', level: 'intermediaire' },
    { id: 'w289', hanzi: '容易', pinyin: 'róng yì', french: 'Facile', theme: 'adjectifs', level: 'intermediaire' },
    { id: 'w290', hanzi: '干净', pinyin: 'gān jìng', french: 'Propre', theme: 'adjectifs', level: 'intermediaire' },
    { id: 'w291', hanzi: '脏', pinyin: 'zāng', french: 'Sale', theme: 'adjectifs', level: 'intermediaire' },
    { id: 'w292', hanzi: '重要', pinyin: 'zhòng yào', french: 'Important', theme: 'adjectifs', level: 'intermediaire' },
    { id: 'w293', hanzi: '有名', pinyin: 'yǒu míng', french: 'Célèbre', theme: 'adjectifs', level: 'intermediaire' },
    { id: 'w294', hanzi: '一样', pinyin: 'yī yàng', french: 'Pareil / Identique', theme: 'adjectifs', level: 'intermediaire' },

    // --- Verbes intermédiaires (25 mots) ---
    { id: 'w295', hanzi: '做', pinyin: 'zuò', french: 'Faire', theme: 'verbes', level: 'intermediaire' },
    { id: 'w296', hanzi: '用', pinyin: 'yòng', french: 'Utiliser', theme: 'verbes', level: 'intermediaire', jpKanji: true, jpNote: '用 = yō/もちいる' },
    { id: 'w297', hanzi: '找', pinyin: 'zhǎo', french: 'Chercher', theme: 'verbes', level: 'intermediaire' },
    { id: 'w298', hanzi: '送', pinyin: 'sòng', french: 'Offrir / Raccompagner', theme: 'verbes', level: 'intermediaire' },
    { id: 'w299', hanzi: '带', pinyin: 'dài', french: 'Apporter / Emmener', theme: 'verbes', level: 'intermediaire' },
    { id: 'w300', hanzi: '开', pinyin: 'kāi', french: 'Ouvrir / Conduire', theme: 'verbes', level: 'intermediaire' },
    { id: 'w301', hanzi: '关', pinyin: 'guān', french: 'Fermer', theme: 'verbes', level: 'intermediaire' },
    { id: 'w302', hanzi: '放', pinyin: 'fàng', french: 'Poser / Mettre', theme: 'verbes', level: 'intermediaire' },
    { id: 'w303', hanzi: '想', pinyin: 'xiǎng', french: 'Vouloir / Penser', theme: 'verbes', level: 'intermediaire' },
    { id: 'w304', hanzi: '要', pinyin: 'yào', french: 'Vouloir / Devoir', theme: 'verbes', level: 'intermediaire' },
    { id: 'w305', hanzi: '能', pinyin: 'néng', french: 'Pouvoir (capacité)', theme: 'verbes', level: 'intermediaire', jpKanji: true, jpNote: '能 = nō (能力) même caractère' },
    { id: 'w306', hanzi: '会', pinyin: 'huì', french: 'Savoir faire / Pouvoir', theme: 'verbes', level: 'intermediaire' },
    { id: 'w307', hanzi: '觉得', pinyin: 'jué de', french: 'Penser / Avoir l\'impression', theme: 'verbes', level: 'intermediaire' },

    // --- Santé & Urgences (15 mots) ---
    { id: 'w308', hanzi: '生病', pinyin: 'shēng bìng', french: 'Tomber malade', theme: 'sante', level: 'intermediaire' },
    { id: 'w309', hanzi: '感冒', pinyin: 'gǎn mào', french: 'Rhume / Attraper froid', theme: 'sante', level: 'intermediaire' },
    { id: 'w310', hanzi: '发烧', pinyin: 'fā shāo', french: 'Avoir de la fièvre', theme: 'sante', level: 'intermediaire' },
    { id: 'w311', hanzi: '咳嗽', pinyin: 'ké sou', french: 'Tousser', theme: 'sante', level: 'intermediaire' },
    { id: 'w312', hanzi: '药', pinyin: 'yào', french: 'Médicament', theme: 'sante', level: 'intermediaire' },
    { id: 'w313', hanzi: '医生', pinyin: 'yī shēng', french: 'Médecin', theme: 'sante', level: 'intermediaire' },
    { id: 'w314', hanzi: '护士', pinyin: 'hù shi', french: 'Infirmier/ière', theme: 'sante', level: 'intermediaire' },

    // --- Sports & Loisirs (12 mots) ---
    { id: 'w315', hanzi: '跑步', pinyin: 'pǎo bù', french: 'Courir / Jogging', theme: 'sport', level: 'intermediaire' },
    { id: 'w316', hanzi: '游泳', pinyin: 'yóu yǒng', french: 'Nager', theme: 'sport', level: 'intermediaire' },
    { id: 'w317', hanzi: '足球', pinyin: 'zú qiú', french: 'Football', theme: 'sport', level: 'intermediaire' },
    { id: 'w318', hanzi: '篮球', pinyin: 'lán qiú', french: 'Basket-ball', theme: 'sport', level: 'intermediaire' },
    { id: 'w319', hanzi: '电影', pinyin: 'diàn yǐng', french: 'Film / Cinéma', theme: 'sport', level: 'intermediaire' },
    { id: 'w320', hanzi: '音乐', pinyin: 'yīn yuè', french: 'Musique', theme: 'sport', level: 'intermediaire', jpKanji: true, jpNote: '音楽 = ongaku. 乐 simplifié de 樂.' },

    // --- Nature & Plantes (12 mots) ---
    { id: 'w321', hanzi: '花', pinyin: 'huā', french: 'Fleur', theme: 'nature', level: 'intermediaire', jpKanji: true, jpNote: '花 = hana, caractère identique.' },
    { id: 'w322', hanzi: '草', pinyin: 'cǎo', french: 'Herbe', theme: 'nature', level: 'intermediaire', jpKanji: true, jpNote: '草 = kusa, identique.' },
    { id: 'w323', hanzi: '树', pinyin: 'shù', french: 'Arbre', theme: 'nature', level: 'intermediaire', jpKanji: true, jpNote: '樹 = ki, simplifié en 树.' },
    { id: 'w324', hanzi: '山', pinyin: 'shān', french: 'Montagne', theme: 'nature', level: 'intermediaire', jpKanji: true, jpNote: '山 = yama, identique.' },
    { id: 'w325', hanzi: '河', pinyin: 'hé', french: 'Rivière', theme: 'nature', level: 'intermediaire' },
    { id: 'w326', hanzi: '海', pinyin: 'hǎi', french: 'Mer', theme: 'nature', level: 'intermediaire', jpKanji: true, jpNote: '海 = umi, identique.' },

    // ============================================================
    // NIVEAU AVANCÉ (~120 mots)
    // ============================================================

    // --- Travail & Société avancé (25 mots) ---
    { id: 'w65', hanzi: '经济', pinyin: 'jīng jì', french: 'Économie', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '経済 = keizai' },
    { id: 'w66', hanzi: '社会', pinyin: 'shè huì', french: 'Société', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '社会 = shakai' },
    { id: 'w67', hanzi: '文化', pinyin: 'wén huà', french: 'Culture', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '文化 = bunka' },
    { id: 'w68', hanzi: '国际', pinyin: 'guó jì', french: 'International', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '国際 = kokusai' },
    { id: 'w69', hanzi: '关系', pinyin: 'guān xì', french: 'Relation / Lien', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '関係 = kankei' },
    { id: 'w70', hanzi: '问题', pinyin: 'wèn tí', french: 'Problème / Question', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '問題 = mondai' },
    { id: 'w71', hanzi: '发展', pinyin: 'fā zhǎn', french: 'Développement', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '発展 = hatten' },
    { id: 'w72', hanzi: '学习', pinyin: 'xué xí', french: 'Étudier / Apprendre', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '学習 = gakushū' },
    { id: 'w74', hanzi: '经验', pinyin: 'jīng yàn', french: 'Expérience', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '経験 = keiken' },
    { id: 'w87', hanzi: '努力', pinyin: 'nǔ lì', french: 'Studieux / Effort', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '努力 = doryoku' },
    { id: 'w327', hanzi: '技术', pinyin: 'jì shù', french: 'Technologie / Technique', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '技術 = gijutsu' },
    { id: 'w328', hanzi: '研究', pinyin: 'yán jiū', french: 'Recherche (scientifique)', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '研究 = kenkyū' },
    { id: 'w329', hanzi: '教育', pinyin: 'jiào yù', french: 'Éducation', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '教育 = kyōiku' },
    { id: 'w330', hanzi: '科学', pinyin: 'kē xué', french: 'Science', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '科学 = kagaku' },
    { id: 'w331', hanzi: '历史', pinyin: 'lì shǐ', french: 'Histoire', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '歴史 = rekishi' },
    { id: 'w332', hanzi: '世界', pinyin: 'shì jiè', french: 'Monde', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '世界 = sekai, mêmes caractères !' },
    { id: 'w333', hanzi: '市场', pinyin: 'shì chǎng', french: 'Marché', theme: 'travail', level: 'avance', jpKanji: true, jpNote: '市場 = ichiba/shijō' },

    // --- Vie quotidienne avancée (30 mots) ---
    { id: 'w73', hanzi: '决定', pinyin: 'jué dìng', french: 'Décider', theme: 'quotidien', level: 'avance', jpKanji: true, jpNote: '決定 = kettei' },
    { id: 'w75', hanzi: '意思', pinyin: 'yì si', french: 'Sens / Signification', theme: 'quotidien', level: 'avance', jpKanji: true, jpNote: '意思 = ishi (intention). Attention au sens !' },
    { id: 'w76', hanzi: '特别', pinyin: 'tè bié', french: 'Spécial', theme: 'quotidien', level: 'avance' },
    { id: 'w77', hanzi: '开始', pinyin: 'kāi shǐ', french: 'Commencer', theme: 'quotidien', level: 'avance', jpKanji: true, jpNote: '開始 = kaishi' },
    { id: 'w78', hanzi: '可以', pinyin: 'kě yǐ', french: 'Pouvoir / Permis', theme: 'quotidien', level: 'avance' },
    { id: 'w79', hanzi: '应该', pinyin: 'yīng gāi', french: 'Devoir (il faut)', theme: 'quotidien', level: 'avance' },
    { id: 'w80', hanzi: '因为', pinyin: 'yīn wèi', french: 'Parce que', theme: 'quotidien', level: 'avance' },
    { id: 'w81', hanzi: '所以', pinyin: 'suǒ yǐ', french: 'Donc', theme: 'quotidien', level: 'avance' },
    { id: 'w82', hanzi: '虽然', pinyin: 'suī rán', french: 'Bien que', theme: 'quotidien', level: 'avance' },
    { id: 'w83', hanzi: '但是', pinyin: 'dàn shì', french: 'Mais / Cependant', theme: 'quotidien', level: 'avance', jpKanji: true, jpNote: '但し (tadashi) en japonais' },
    { id: 'w84', hanzi: '已经', pinyin: 'yǐ jīng', french: 'Déjà', theme: 'quotidien', level: 'avance', jpKanji: true, jpNote: '已經 = sudeni' },
    { id: 'w85', hanzi: '可能', pinyin: 'kě néng', french: 'Peut-être / Possible', theme: 'quotidien', level: 'avance', jpKanji: true, jpNote: '可能 = kanō' },
    { id: 'w86', hanzi: '漂亮', pinyin: 'piào liang', french: 'Beau / Jolie', theme: 'quotidien', level: 'avance' },
    { id: 'w334', hanzi: '方便', pinyin: 'fāng biàn', french: 'Pratique / Convenable', theme: 'quotidien', level: 'avance', jpKanji: true, jpNote: '方便 = hōben (expédient)' },
    { id: 'w335', hanzi: '马上', pinyin: 'mǎ shàng', french: 'Tout de suite', theme: 'quotidien', level: 'avance' },
    { id: 'w336', hanzi: '从来', pinyin: 'cóng lái', french: 'Depuis toujours / Jamais (négatif)', theme: 'quotidien', level: 'avance' },
    { id: 'w337', hanzi: '一直', pinyin: 'yī zhí', french: 'Toujours / Continuellement', theme: 'quotidien', level: 'avance' },
    { id: 'w338', hanzi: '一起', pinyin: 'yī qǐ', french: 'Ensemble', theme: 'quotidien', level: 'avance' },
    { id: 'w339', hanzi: '经常', pinyin: 'jīng cháng', french: 'Souvent', theme: 'quotidien', level: 'avance' },
    { id: 'w340', hanzi: '有时候', pinyin: 'yǒu shí hou', french: 'Quelquefois', theme: 'quotidien', level: 'avance' },
    { id: 'w341', hanzi: '总是', pinyin: 'zǒng shì', french: 'Toujours (tout le temps)', theme: 'quotidien', level: 'avance' },
    { id: 'w342', hanzi: '几乎', pinyin: 'jī hū', french: 'Presque', theme: 'quotidien', level: 'avance' },
    { id: 'w343', hanzi: '其实', pinyin: 'qí shí', french: 'En réalité / En fait', theme: 'quotidien', level: 'avance' },
    { id: 'w344', hanzi: '终于', pinyin: 'zhōng yú', french: 'Enfin / Finalement', theme: 'quotidien', level: 'avance' },

    // --- Verbes avancés (20 mots) ---
    { id: 'w346', hanzi: '变成', pinyin: 'biàn chéng', french: 'Devenir', theme: 'verbes', level: 'avance' },
    { id: 'w347', hanzi: '改变', pinyin: 'gǎi biàn', french: 'Changer', theme: 'verbes', level: 'avance', jpKanji: true, jpNote: '改變 = 変更 (henkō)' },
    { id: 'w348', hanzi: '继续', pinyin: 'jì xù', french: 'Continuer', theme: 'verbes', level: 'avance', jpKanji: true, jpNote: '継続 = keizoku' },
    { id: 'w349', hanzi: '完成', pinyin: 'wán chéng', french: 'Achever / Accomplir', theme: 'verbes', level: 'avance', jpKanji: true, jpNote: '完成 = kansei, mêmes caractères !' },
    { id: 'w350', hanzi: '提高', pinyin: 'tí gāo', french: 'Améliorer / Augmenter', theme: 'verbes', level: 'avance' },
    { id: 'w351', hanzi: '减少', pinyin: 'jiǎn shǎo', french: 'Réduire / Diminuer', theme: 'verbes', level: 'avance' },
    { id: 'w352', hanzi: '产生', pinyin: 'chǎn shēng', french: 'Produire / Générer', theme: 'verbes', level: 'avance' },
    { id: 'w353', hanzi: '表示', pinyin: 'biǎo shì', french: 'Exprimer / Montrer', theme: 'verbes', level: 'avance', jpKanji: true, jpNote: '表示 = hyōji (affichage)' },
    { id: 'w354', hanzi: '认为', pinyin: 'rèn wéi', french: 'Estimer / Considérer que', theme: 'verbes', level: 'avance' },
    { id: 'w355', hanzi: '相信', pinyin: 'xiāng xìn', french: 'Croire (qqn / qqch)', theme: 'verbes', level: 'avance', jpKanji: true, jpNote: '相信 = 信用 (shin\'yō)' },
    { id: 'w356', hanzi: '参加', pinyin: 'cān jiā', french: 'Participer', theme: 'verbes', level: 'avance' },
    { id: 'w357', hanzi: '帮助', pinyin: 'bāng zhù', french: 'Aider', theme: 'verbes', level: 'avance' },
    { id: 'w358', hanzi: '告诉', pinyin: 'gào sù', french: 'Dire / Informer', theme: 'verbes', level: 'avance' },
    { id: 'w359', hanzi: '回答', pinyin: 'huí dá', french: 'Répondre', theme: 'verbes', level: 'avance', jpKanji: true, jpNote: '回答 = kaitō, mêmes caractères.' },

    // --- Adjectifs avancés (15 mots) ---
    { id: 'w360', hanzi: '幸福', pinyin: 'xìng fú', french: 'Heureux / Bienheureux', theme: 'adjectifs', level: 'avance', jpKanji: true, jpNote: '幸福 = kōfuku, mêmes caractères.' },
    { id: 'w361', hanzi: '可怜', pinyin: 'kě lián', french: 'Pauvre / Pitoyable', theme: 'adjectifs', level: 'avance' },
    { id: 'w362', hanzi: '可怕', pinyin: 'kě pà', french: 'Effrayant', theme: 'adjectifs', level: 'avance' },
    { id: 'w363', hanzi: '可爱', pinyin: 'kě ài', french: 'Mignon / Adorable', theme: 'adjectifs', level: 'avance' },
    { id: 'w364', hanzi: '严格', pinyin: 'yán gé', french: 'Strict / Sévère', theme: 'adjectifs', level: 'avance' },
    { id: 'w365', hanzi: '安全', pinyin: 'ān quán', french: 'Sûr / En sécurité', theme: 'adjectifs', level: 'avance', jpKanji: true, jpNote: '安全 = anzen, mêmes caractères.' },
    { id: 'w366', hanzi: '危险', pinyin: 'wēi xiǎn', french: 'Dangereux', theme: 'adjectifs', level: 'avance', jpKanji: true, jpNote: '危險 = kiken. 危 = abunai, même caractère.' },
    { id: 'w367', hanzi: '简单', pinyin: 'jiǎn dān', french: 'Simple', theme: 'adjectifs', level: 'avance', jpKanji: true, jpNote: '簡單 = kantan' },
    { id: 'w368', hanzi: '复杂', pinyin: 'fù zá', french: 'Complexe', theme: 'adjectifs', level: 'avance', jpKanji: true, jpNote: '複雜 = fukuzatsu' },
    { id: 'w369', hanzi: '熟悉', pinyin: 'shú xī', french: 'Familier / Connaître bien', theme: 'adjectifs', level: 'avance' },
    { id: 'w370', hanzi: '陌生', pinyin: 'mò shēng', french: 'Inconnu / Étranger', theme: 'adjectifs', level: 'avance' },

    // --- Conjonctions & Adverbes (15 mots) ---
    { id: 'w371', hanzi: '然后', pinyin: 'rán hòu', french: 'Ensuite / Puis', theme: 'quotidien', level: 'avance' },
    { id: 'w372', hanzi: '而且', pinyin: 'ér qiě', french: 'De plus / En outre', theme: 'quotidien', level: 'avance' },
    { id: 'w373', hanzi: '或者', pinyin: 'huò zhě', french: 'Ou (bien)', theme: 'quotidien', level: 'avance' },
    { id: 'w374', hanzi: '还是', pinyin: 'hái shì', french: 'Ou (dans une question)', theme: 'quotidien', level: 'avance' },
    { id: 'w375', hanzi: '只要', pinyin: 'zhǐ yào', french: 'Pourvu que / Il suffit de', theme: 'quotidien', level: 'avance' },
    { id: 'w376', hanzi: '只有', pinyin: 'zhǐ yǒu', french: 'Seulement si', theme: 'quotidien', level: 'avance' },
    { id: 'w377', hanzi: '除了', pinyin: 'chú le', french: 'Sauf / Excepté', theme: 'quotidien', level: 'avance' },
    { id: 'w378', hanzi: '关于', pinyin: 'guān yú', french: 'À propos de / Concernant', theme: 'quotidien', level: 'avance' },
    { id: 'w379', hanzi: '对于', pinyin: 'duì yú', french: 'Envers / Pour', theme: 'quotidien', level: 'avance' },

    // === HSK 1 ajoutés ===
    { id: 'w382', hanzi: '我', pinyin: 'wǒ', french: 'Je / Moi', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: 'Même caractère qu\'en japonais (watashi).' },
    { id: 'w383', hanzi: '你', pinyin: 'nǐ', french: 'Tu / Toi', theme: 'quotidien', level: 'debutant' },
    { id: 'w384', hanzi: '他', pinyin: 'tā', french: 'Il / Lui', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '他 = ta (il) en chinois. En japonais, 他 = hoka (autre) — faux ami !' },
    { id: 'w385', hanzi: '她', pinyin: 'tā', french: 'Elle', theme: 'quotidien', level: 'debutant' },
    { id: 'w386', hanzi: '我们', pinyin: 'wǒ men', french: 'Nous', theme: 'quotidien', level: 'debutant' },
    { id: 'w387', hanzi: '人', pinyin: 'rén', french: 'Personne / Être humain', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '人 = rén (personne). En japonais, 人 = hito. Même caractère.' },
    { id: 'w388', hanzi: '是', pinyin: 'shì', french: 'Être', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: 'Verbe \"être\". En japonais : は/です. Structure très différente !' },
    { id: 'w389', hanzi: '有', pinyin: 'yǒu', french: 'Avoir / Il y a', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '有 = yǒu. En japonais, 有る = aru (exister).' },
    { id: 'w390', hanzi: '叫', pinyin: 'jiào', french: 'S\'appeler / S\'appelle', theme: 'quotidien', level: 'debutant' },
    { id: 'w391', hanzi: '爱', pinyin: 'ài', french: 'Aimer (qqn / passion)', theme: 'emotions', level: 'debutant', jpKanji: true, jpNote: '愛 = ai. Même caractère qu\'en japonais (戀/恋 = koi pour l\'amour romantique).' },
    { id: 'w392', hanzi: '在', pinyin: 'zài', french: 'Être à / Se trouver', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '在 = zài (être à). En japonais : 在る = aru.' },
    { id: 'w393', hanzi: '回', pinyin: 'huí', french: 'Retourner', theme: 'verbes', level: 'debutant', jpKanji: true, jpNote: '回 = huí. En japonais : 回る = mawaru (tourner). Sens proche.' },
    { id: 'w394', hanzi: '看见', pinyin: 'kàn jiàn', french: 'Voir / Apercevoir', theme: 'verbes', level: 'debutant' },
    { id: 'w395', hanzi: '睡觉', pinyin: 'shuì jiào', french: 'Dormir / Se coucher', theme: 'verbes', level: 'debutant' },
    { id: 'w396', hanzi: '打电话', pinyin: 'dǎ diàn huà', french: 'Téléphoner', theme: 'verbes', level: 'debutant' },
    { id: 'w397', hanzi: '工作', pinyin: 'gōng zuò', french: 'Travail / Travailler', theme: 'travail', level: 'debutant', jpKanji: true, jpNote: '工作 = gōngzuò. En japonais : 工作 = kōsaku (travail manuel).' },
    { id: 'w398', hanzi: '的', pinyin: 'de', french: '(particule possessive)', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '的 = de. Comme の en japonais pour la possession.' },
    { id: 'w399', hanzi: '了', pinyin: 'le', french: '(particule d\'accompli / changement)', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '了 = le. N\'a rien à voir avec 了 (ryō/了承) en japonais.' },
    { id: 'w400', hanzi: '不', pinyin: 'bù', french: 'Non / Ne...pas', theme: 'quotidien', level: 'debutant' },
    { id: 'w401', hanzi: '没有', pinyin: 'méi yǒu', french: 'Ne pas avoir / Il n\'y a pas', theme: 'quotidien', level: 'debutant' },
    { id: 'w402', hanzi: '吗', pinyin: 'ma', french: '(particule interrogative oui/non)', theme: 'quotidien', level: 'debutant' },
    { id: 'w403', hanzi: '呢', pinyin: 'ne', french: '(particule : et...? / action en cours)', theme: 'quotidien', level: 'debutant' },
    { id: 'w404', hanzi: '和', pinyin: 'hé', french: 'Et (conjonction)', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '和 = hé (et). En japonais : 和 = wa (paix/japonais). Sens différent !' },
    { id: 'w405', hanzi: '什么', pinyin: 'shén me', french: 'Quoi / Quel(le)', theme: 'quotidien', level: 'debutant' },
    { id: 'w406', hanzi: '谁', pinyin: 'shéi', french: 'Qui', theme: 'quotidien', level: 'debutant' },
    { id: 'w407', hanzi: '哪', pinyin: 'nǎ', french: 'Quel (parmi plusieurs)', theme: 'quotidien', level: 'debutant' },
    { id: 'w408', hanzi: '怎么', pinyin: 'zěn me', french: 'Comment', theme: 'quotidien', level: 'debutant' },
    { id: 'w409', hanzi: '这', pinyin: 'zhè', french: 'Ce / Cette / Ici', theme: 'quotidien', level: 'debutant' },
    { id: 'w410', hanzi: '那', pinyin: 'nà', french: 'Ce...là / Là-bas', theme: 'quotidien', level: 'debutant' },
    { id: 'w411', hanzi: '很', pinyin: 'hěn', french: 'Très', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '很 = hěn (très). En japonais : 很 est rare, mais 狠 = hěn (cruel). Ne pas confondre.' },
    { id: 'w412', hanzi: '太', pinyin: 'tài', french: 'Trop / Très (intensité)', theme: 'quotidien', level: 'debutant' },
    { id: 'w413', hanzi: '都', pinyin: 'dōu', french: 'Tout / Tous', theme: 'quotidien', level: 'debutant' },
    { id: 'w414', hanzi: '上', pinyin: 'shàng', french: 'Sur / Monter', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '上 = shàng. En japonais : ue/上 (dessus). Même caractère.' },
    { id: 'w415', hanzi: '下', pinyin: 'xià', french: 'Sous / Descendre', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '下 = xià. En japonais : shita/下 (dessous). Même caractère.' },
    { id: 'w416', hanzi: '里', pinyin: 'lǐ', french: 'Dans / À l\'intérieur', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '里 = lǐ. En japonais : 里 = sato (village). Sens différent !' },
    { id: 'w417', hanzi: '个', pinyin: 'gè', french: '(classificateur universel)', theme: 'nombres', level: 'debutant' },
    { id: 'w418', hanzi: '块', pinyin: 'kuài', french: 'Yuan / Morceau', theme: 'nombres', level: 'debutant' },
    { id: 'w419', hanzi: '岁', pinyin: 'suì', french: 'An (âge)', theme: 'nombres', level: 'debutant', jpKanji: true, jpNote: '歳 = sai (âge). Même sens qu\'en japonais !' },
    { id: 'w420', hanzi: '本', pinyin: 'běn', french: '(classif. livres/cahiers)', theme: 'nombres', level: 'debutant', jpKanji: true, jpNote: '本 = běn. En japonais : 本 = hon (livre). Même caractère !' },
    { id: 'w421', hanzi: '些', pinyin: 'xiē', french: 'Quelques / Un peu de', theme: 'nombres', level: 'debutant' },
    { id: 'w422', hanzi: '先生', pinyin: 'xiān sheng', french: 'Monsieur / Mari', theme: 'famille', level: 'debutant', jpKanji: true, jpNote: '先生 = xiānsheng. En japonais : 先生 = sensei (professeur). Faux ami partiel !' },
    { id: 'w423', hanzi: '北京', pinyin: 'Běi jīng', french: 'Pékin', theme: 'voyage', level: 'debutant' },
    { id: 'w424', hanzi: '时候', pinyin: 'shí hou', french: 'Moment / Période', theme: 'temps', level: 'debutant' },
    { id: 'w425', hanzi: '上午', pinyin: 'shàng wǔ', french: 'Matin (avant midi)', theme: 'temps', level: 'debutant' },
    { id: 'w426', hanzi: '东西', pinyin: 'dōng xi', french: 'Chose / Objet', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '东西 = dōngxi (chose). En japonais : 東西 = tōzai (est-ouest/direction).' },
    { id: 'w427', hanzi: '菜', pinyin: 'cài', french: 'Plat / Légume / Cuisine', theme: 'nourriture', level: 'debutant' },
    { id: 'w428', hanzi: '点', pinyin: 'diǎn', french: 'Heure / Point / Un peu', theme: 'temps', level: 'debutant' },
    { id: 'w429', hanzi: '电视', pinyin: 'diàn shì', french: 'Télévision', theme: 'quotidien', level: 'debutant' },
    { id: 'w430', hanzi: '字', pinyin: 'zì', french: 'Caractère / Mot écrit', theme: 'travail', level: 'debutant', jpKanji: true, jpNote: '字 = zì. En japonais : 字 = ji (caractère). Même sens !' },
    { id: 'w431', hanzi: '杯子', pinyin: 'bēi zi', french: 'Tasse / Verre', theme: 'maison', level: 'debutant' },

    // === Mots manquants restaurés ===
    { id: 'w28', hanzi: '水', pinyin: 'shuǐ', french: 'Eau', theme: 'nourriture', level: 'debutant', jpKanji: true, jpNote: '水 = mizu/すい' },
    { id: 'w29', hanzi: '茶', pinyin: 'chá', french: 'Thé', theme: 'nourriture', level: 'debutant', jpKanji: true, jpNote: '茶 = cha, prononciation proche !' },
    { id: 'w30', hanzi: '咖啡', pinyin: 'kā fēi', french: 'Café', theme: 'nourriture', level: 'debutant' },
    { id: 'w32', hanzi: '书', pinyin: 'shū', french: 'Livre', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '书 = 書 (sho/かく)' },
    { id: 'w33', hanzi: '电话', pinyin: 'diàn huà', french: 'Téléphone', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '電話 = denwa, identique !' },
    { id: 'w34', hanzi: '电脑', pinyin: 'diàn nǎo', french: 'Ordinateur', theme: 'quotidien', level: 'debutant', jpKanji: true, jpNote: '电 + 脑 = "cerveau électrique". En japonais on dit コンピュータ (konpyūta), pas 電脳 (vieux).' },
    { id: 'w35', hanzi: '手表', pinyin: 'shǒu biǎo', french: 'Montre (poignet)', theme: 'quotidien', level: 'debutant' },

    // === Fin du vocabulaire ===
  ],
};

export default vocabularyData;
